[package]
name = "oauth_decap_github"
version = "0.0.1"
edition = "2021"
authors = ["Augusto Gunsch <augusto@augustogunsch>"]
license = "MIT"
repository = "https://github.com/augustogunsch/oauth_decap_github_lib"
description = """
OAuth server for Decap CMS for GitHub.
"""

[dependencies]
axum = "0.7"
oauth_decap_github_lib = "0.0.3"
tokio = { version = "1", features=["full"] }
